### ISSUE TITLE
Surface API issues

### ISSUE THREAD

**Issue by domenic** [WICG/PEPC#5]
Per https://w3ctag.github.io/design-principles/#casing-rules, `icon-style` should be `iconstyle`.

Per https://github.com/w3ctag/design-principles/issues/280, `dismissed` and `resolved` should be `dismiss` and `resolve`.

Note that "resolve" in web API design usually refers to promises. I'd suggest "change".

To match other HTML elements, the IDL event handlers `onresolve` and `ondismiss` should be on [`GlobalEventHandlers`](https://html.spec.whatwg.org/#globaleventhandlers), not on `HTMLPermissionElement`.

**Comment by andypaicu** [comment]
I'm making some of these changes in https://github.com/WICG/PEPC/pull/6. 

I want to discuss the naming a bit more since I realize the original explainer gave a misleading description of the intent behind the `onresolve` event. 
The feedback we've received is that it would be useful for the developer flow to know when the user has closed the PEPC-triggered permission prompt, and to be able to distinguish between this being done by dismissing the UI (e.g. the 'x' button) or by taking some action on the prompt itself. That is the motivation behind these 2 events.
Therefore I'm thinking maybe `onpromptdismiss` and `onpromptaction` or something similar. Or maybe combined into one single `onclose` event if it's still possible to distinguish between dismiss/non-dismiss.

**Comment by marcoscaceres** [comment]
Same, these names are better.

**Comment by andypaicu** [comment]
The event names were the remaining pieces of feedback that were not addressed. With https://github.com/WICG/PEPC/pull/9 closing this, feel free to re-open if I missed something.
